"""Adding relationships

Revision ID: ad8dd20c5e96
Revises: 6845c56ec213
Create Date: 2024-01-02 23:30:03.589858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8dd20c5e96'
down_revision = '6845c56ec213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_occupied_classroom_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], )
    )
    op.create_table('user_request_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], )
    )
    with op.batch_alter_table('classroom_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'building_table', ['building_id'], ['id'])
        batch_op.create_foreign_key(None, 'department_table', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_table', ['manager_id'], ['id'])

    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['manager_id'])

    with op.batch_alter_table('request_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_table', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'classroom_table', ['classroom_id'], ['id'])

    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'department_table', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('request_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('classroom_id')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('department_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('manager_id')

    with op.batch_alter_table('classroom_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('manager_id')
        batch_op.drop_column('department_id')
        batch_op.drop_column('building_id')

    op.drop_table('user_request_association')
    op.drop_table('user_occupied_classroom_association')
    # ### end Alembic commands ###
