"""Adding new field into user model

Revision ID: decedf7b02bd
Revises: ad8dd20c5e96
Create Date: 2024-01-03 17:13:01.251671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decedf7b02bd'
down_revision = 'ad8dd20c5e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
